version: "3.5"

volumes:
  postgres:
  pgadmin4:

networks:
  dev-postgres:
    name: dev.postgres

services:
  postgres:
    image: postgres
    container_name: dev.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - dev-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: dev.pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.local
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - dev-postgres
    ports:
      - 8889:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
