version: "3.5"

volumes:
  postgres:
  pgadmin4:

networks:
  dev-postgres:
    name: dev.postgres

services:
  postgres:
    image: postgres
    container_name: dev.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dev-postgres
    ports:
      - 54320:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: dev.pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - dev-postgres
    ports:
      - 54321:80
    volumes:
      - pgadmin4:/var/lib/pgadmin